import type { Metadata } from "next";
import "./globals.css";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased" style={{ fontFamily: "'Bai Jamjuree', Arial, Helvetica, sans-serif", fontWeight: 300, background: '#ffffff', color: '#2c3c5c' }}>
        {children}
      </body>
    </html>
  );
}
